// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityEventManager.API.Data;

#nullable disable

namespace UniversityEventManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707214738_IntegratePr2DbSchema")]
    partial class IntegratePr2DbSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UniversityEventManager.API.Models.Attendance", b =>
                {
                    b.Property<long>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attendanceID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AttendanceID"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("checked_in")
                        .HasColumnName("attendanceStatus");

                    b.Property<DateTime>("CheckInDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checkInDatetime");

                    b.Property<long>("CheckedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("checkedBy");

                    b.Property<long>("RegistrationID")
                        .HasColumnType("bigint")
                        .HasColumnName("registrationID");

                    b.HasKey("AttendanceID");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("RegistrationID")
                        .IsUnique();

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.Event", b =>
                {
                    b.Property<long>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EventID"));

                    b.Property<long>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("approvedBy");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<long>("CreationRequestID")
                        .HasColumnType("bigint")
                        .HasColumnName("creationRequestID");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endDatetime");

                    b.Property<string>("EventStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("upcoming")
                        .HasColumnName("eventStatus");

                    b.Property<long>("OrganiserID")
                        .HasColumnType("bigint")
                        .HasColumnName("organiserID");

                    b.Property<string>("PosterS3Key")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("posterS3Key");

                    b.Property<string>("PosterURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("posterURL");

                    b.Property<DateTime>("StartDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startDatetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("venue");

                    b.HasKey("EventID");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreationRequestID")
                        .IsUnique();

                    b.HasIndex("OrganiserID");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.EventCategory", b =>
                {
                    b.Property<long>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("categoryID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("event_categories", (string)null);
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.EventCreationRequest", b =>
                {
                    b.Property<long>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("requestID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RequestID"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryID");

                    b.Property<string>("EventDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("eventDescription");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("eventTitle");

                    b.Property<string>("PosterS3Key")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("posterS3Key");

                    b.Property<string>("PosterURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("posterURL");

                    b.Property<DateTime>("ProposedEndDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("proposedEndDatetime");

                    b.Property<DateTime>("ProposedStartDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("proposedStartDatetime");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("remark");

                    b.Property<int>("RequestCapacity")
                        .HasColumnType("int")
                        .HasColumnName("requestCapacity");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("requestedStatus");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewedAt");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewedBy");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submittedAt");

                    b.Property<long>("SubmittedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("submittedBy");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("venue");

                    b.HasKey("RequestID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("SubmittedBy");

                    b.ToTable("event_creation_request", (string)null);
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.Registration", b =>
                {
                    b.Property<long>("RegistrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("registrationID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RegistrationID"));

                    b.Property<long>("EventID")
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("qrCode");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("registrationDate");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("registered")
                        .HasColumnName("registrationStatus");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint")
                        .HasColumnName("userID");

                    b.HasKey("RegistrationID");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.HasIndex("EventID", "UserID")
                        .IsUnique();

                    b.ToTable("registrations", (string)null);
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("userID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserID"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("accountStatus");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fullName");

                    b.Property<string>("Organisation")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("organisation");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("roleID");

                    b.Property<string>("SchoolID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("schoolID");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("SchoolID")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.Attendance", b =>
                {
                    b.HasOne("UniversityEventManager.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CheckedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityEventManager.API.Models.Registration", null)
                        .WithMany()
                        .HasForeignKey("RegistrationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.Event", b =>
                {
                    b.HasOne("UniversityEventManager.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityEventManager.API.Models.EventCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityEventManager.API.Models.EventCreationRequest", null)
                        .WithMany()
                        .HasForeignKey("CreationRequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityEventManager.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OrganiserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.EventCreationRequest", b =>
                {
                    b.HasOne("UniversityEventManager.API.Models.EventCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityEventManager.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityEventManager.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.Registration", b =>
                {
                    b.HasOne("UniversityEventManager.API.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityEventManager.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityEventManager.API.Models.User", b =>
                {
                    b.HasOne("UniversityEventManager.API.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
