// <auto-generated />
using System;
using EventManagementSystem_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManagementSystem_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260704142920_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Attendance", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attendanceID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AttendanceId"));

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("attendanceStatus");

                    b.Property<DateTime>("CheckInDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checkInDatetime");

                    b.Property<long>("CheckedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("checkedBy");

                    b.Property<long>("RegistrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("registrationID");

                    b.HasKey("AttendanceId");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EventId"));

                    b.Property<long>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("approvedBy");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<long>("CreationRequestID")
                        .HasColumnType("bigint")
                        .HasColumnName("creationRequestID");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endDatetime");

                    b.Property<string>("EventStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("eventStatus");

                    b.Property<long>("OrganiserID")
                        .HasColumnType("bigint")
                        .HasColumnName("organiserID");

                    b.Property<string>("PosterURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("posterURL");

                    b.Property<DateTime>("StartDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startDatetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("venue");

                    b.HasKey("EventId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreationRequestID")
                        .IsUnique();

                    b.HasIndex("OrganiserID");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.EventCategory", b =>
                {
                    b.Property<long>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("categoryID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("event_categories", (string)null);
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.EventCreationRequest", b =>
                {
                    b.Property<long>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("requestID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RequestID"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryID");

                    b.Property<string>("EventDescription")
                        .HasColumnType("text")
                        .HasColumnName("eventDescription");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("eventTitle");

                    b.Property<string>("PosterS3Key")
                        .HasColumnType("longtext");

                    b.Property<string>("PosterURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("posterURL");

                    b.Property<DateTime>("ProposedEndDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("proposedEndDatetime");

                    b.Property<DateTime>("ProposedStartDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("proposedStartDatetime");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("remark");

                    b.Property<int>("RequestCapacity")
                        .HasColumnType("int")
                        .HasColumnName("requestCapacity");

                    b.Property<string>("RequestedStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("requestedStatus");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewedAt");

                    b.Property<long?>("ReviewedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewedBy");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submittedAt");

                    b.Property<long>("SubmittedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("submittedBy");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("venue");

                    b.HasKey("RequestID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("SubmittedBy");

                    b.ToTable("event_creation_request", (string)null);
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Registration", b =>
                {
                    b.Property<long>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("registrationID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RegistrationId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("qrCode");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("registrationDate");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("registrationStatus");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userID");

                    b.HasKey("RegistrationId");

                    b.HasIndex("EventId");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("registrations", (string)null);
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usersID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("accountStatus");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fullName");

                    b.Property<string>("Organisation")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("organisation");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleID");

                    b.Property<string>("SchoolID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("schoolID");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("SchoolID")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Attendance", b =>
                {
                    b.HasOne("EventManagementSystem_Backend.Models.User", "CheckedByUser")
                        .WithMany("CheckedAttendances")
                        .HasForeignKey("CheckedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventManagementSystem_Backend.Models.Registration", "Registration")
                        .WithOne("Attendance")
                        .HasForeignKey("EventManagementSystem_Backend.Models.Attendance", "RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckedByUser");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Event", b =>
                {
                    b.HasOne("EventManagementSystem_Backend.Models.User", "Approver")
                        .WithMany("ApprovedEvents")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventManagementSystem_Backend.Models.EventCategory", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventManagementSystem_Backend.Models.EventCreationRequest", "CreationRequest")
                        .WithOne("Event")
                        .HasForeignKey("EventManagementSystem_Backend.Models.Event", "CreationRequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventManagementSystem_Backend.Models.User", "Organiser")
                        .WithMany("OrganisedEvents")
                        .HasForeignKey("OrganiserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Category");

                    b.Navigation("CreationRequest");

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.EventCreationRequest", b =>
                {
                    b.HasOne("EventManagementSystem_Backend.Models.EventCategory", "Category")
                        .WithMany("EventCreationRequests")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventManagementSystem_Backend.Models.User", "ReviewedByUser")
                        .WithMany("ReviewedRequests")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EventManagementSystem_Backend.Models.User", "SubmittedByUser")
                        .WithMany("SubmittedRequests")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Registration", b =>
                {
                    b.HasOne("EventManagementSystem_Backend.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventManagementSystem_Backend.Models.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.User", b =>
                {
                    b.HasOne("EventManagementSystem_Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.EventCategory", b =>
                {
                    b.Navigation("EventCreationRequests");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.EventCreationRequest", b =>
                {
                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Registration", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EventManagementSystem_Backend.Models.User", b =>
                {
                    b.Navigation("ApprovedEvents");

                    b.Navigation("CheckedAttendances");

                    b.Navigation("OrganisedEvents");

                    b.Navigation("Registrations");

                    b.Navigation("ReviewedRequests");

                    b.Navigation("SubmittedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
