// <auto-generated />
using EventManagementSystem_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventManagementSystem_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706000000_schema_cleanup_userid_uniques_s3key")]
    partial class schema_cleanup_userid_uniques_s3key
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);
#pragma warning restore 612, 618
        }
    }
}
